# Generated by Django 5.1.2 on 2024-10-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('InvoiceNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=30)),
                ('BillingAddress', models.TextField()),
                ('ShippingAddress', models.TextField()),
                ('GSTIN', models.CharField(max_length=30)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryName', models.CharField(max_length=30)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('InvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.invoiceheader')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=30)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('InvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.invoiceheader')),
            ],
        ),
    ]
