# Generated by Django 5.1.2 on 2024-10-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceheader',
            name='InvoiceBillSundry',
            field=models.ManyToManyField(to='bills.invoicebillsundry'),
        ),
        migrations.AddField(
            model_name='invoiceheader',
            name='InvoiceItems',
            field=models.ManyToManyField(to='bills.invoiceitems'),
        ),
    ]
